### ISSUE TITLE
Build Initial Project Structure

### ISSUE THREAD

**Issue by brunomachadors** [brunomachadors/portfolio#1]
# Build Initial Project Structure

## Description

As part of setting up the project, we need to create a clean and organized base structure. This task involves:

1. Structuring the application with a basic layout that includes:
   - **Header**
   - **Main**
   - **Footer**
2. Removing default styles from the Next.js installation to ensure a clean slate for custom styling.
3. Preparing the project to work with a simple, minimalistic layout to support future components and pages.

---

## Tasks

- [x] **Create Base Layout Component:**
  - Create a `Layout` component that wraps the entire application with the following structure:
    ```jsx
    <div>
      <header>Header Content</header>
      <main>Main Content</main>
      <footer>Footer Content</footer>
    </div>
    ```

- [x] **Implement the Layout in `_app.tsx`:**
  - Import the `Layout` component into the file `src/pages/_app.tsx` and wrap all pages with it.

- [x] **Clean Default Styles:**
  - Open the `globals.css` file located in `src/styles/` (or where styles are defined) and remove all unnecessary styles.

- [x] **Define Basic Styles:**
  - Add minimal styles for the layout in `globals.css` or Tailwind classes in the layout component:
    ```css
    body {
      margin: 0;
      font-family: Arial, sans-serif; /* or your preferred font */
    }
    header, footer {
      padding: 1rem;
      background-color: #f4f4f4; /* Simple background color */
    }
    main {
      padding: 1rem;
    }
    ```

- [x] **Test the Layout:**
  - Start the development server with `npm run dev` and ensure the layout is rendered correctly with no default styles interfering.

---

## Outcome

By completing this issue, the project will have:
- A basic and clean structure to build upon.
- A reusable layout with a header, main content area, and footer.
- Default styles removed to allow for custom design and development.
